services:
  yolo_flask:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ${DB_ROOT}/images:/images:ro
      - ${DB_ROOT}/cropped:/cropped
